CONFIG_TOOLCHAIN_PATH="/opt/arm-AX620E-linux-uclibcgnueabihf/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-AX620E-linux-uclibcgnueabihf-"
CONFIG_AX_MSP_ENABLED=y
CONFIG_AX_620QP_MSP_ENABLED=y
CONFIG_AX20QP_MSP_V3_0_0_ENABLED=y