CROSS_DIR := /opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin
CROSS := aarch64-linux-gnu-
PUSH_URL:=192.168.31.202
PUSH_DIR:=/home/nihao
SSH_USER:=
SSH_PASSWORLD:=

include ../../tools/Makefile.mk
