
# CONFIG_COMPONENT1_ENABLED=y

CONFIG_TOOLCHAIN_PATH="/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin"
CONFIG_TOOLCHAIN_PREFIX="aarch64-none-linux-gnu-"
CONFIG_CPU_ARCH="armv8"
CONFIG_LHV_ENABLED=y
CONFIG_LHV_WITH_EVPP=y
CONFIG_LHV_WITH_HTTP=y
CONFIG_D_HAL_ENABLED=y
CONFIG_D_HAL_LOCAL_ENABLED=y