// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: core135_for_ax630c_kit

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void kit_led_switch_call(lv_event_t * e);
void kit_emmc_test_call(lv_event_t * e);
void kit_sd_test_call(lv_event_t * e);
void kit_otg_test_call(lv_event_t * e);
void kit_i2c_test_call(lv_event_t * e);
void kit_io_test_call(lv_event_t * e);
void kit_touch_test_call(lv_event_t * e);
void kit_csi_dsi_test_call(lv_event_t * e);
void kit_cmm_test_call(lv_event_t * e);
void kit_wifi_test_call(lv_event_t * e);
void kit_play_cap_test_call(lv_event_t * e);
void kit_cap_test_call(lv_event_t * e);
void kit_play_logo_test_call(lv_event_t * e);
void kit_load_test_call(lv_event_t * e);
void kit_power_test_call(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
