CONFIG_TOOLCHAIN_PATH="/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin"
CONFIG_TOOLCHAIN_PREFIX="aarch64-none-linux-gnu-"

# CONFIG_COMMPILE_DEBUG=y
CONFIG_AX_MSP_ENABLED=y
CONFIG_AX_620E_MSP_ENABLED=y
# CONFIG_AX630C_OPENWRT_SDK_ENABLED=y
# CONFIG_DEVICE_DRIVER_ENABLED=y
# CONFIG_DEVICE_UART_ENABLED=y
# CONFIG_LHV_ENABLED=y
# CONFIG_LHV_WITH_KCP is not set
# CONFIG_LHV_WITH_PROTOCOL is not set
# CONFIG_LHV_WITH_EVPP=y
CONFIG_UTILITIES_ENABLED=y
CONFIG_BACKWARD_CPP_ENABLED=y
CONFIG_TOOLCHAIN_FLAGS="-g"
# CONFIG_EVENTPP_ENABLED=y
# CONFIG_LHV_ENABLED=y
# CONFIG_LHV_WITH_EVPP=y
# CONFIG_EVENTPP_ENABLED=y
# CONFIG_STACKFLOW_ENABLED=y
CONFIG_UTILITIES_BASE64_ENABLED=y
CONFIG_SINGLE_HEADER_LIBS_ENABLED=y
CONFIG_AX_COMMON_HAL_ENABLED=y
CONFIG_SAMPLE_COMMON_ENABLED=y
CONFIG_MSP_V2_0_0_ENABLED=y