# project_root/src/SConscript
import os
# Import the environment from the SConstruct file
Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())



SRCS = Glob('src/*.c*')
INCLUDE = [ADir('include'), ADir('.')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['pthread', 'utilities']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []


export_conanenv()
CONANDEPS = "../build/Release/generators/SConscript_conandeps"
if not os.path.exists(CONANDEPS):
    os.system("conan install .. --profile:host=../build/config/corss-toolchina  --build=missing")
if os.path.exists(CONANDEPS):
    conandeps = SConscript(CONANDEPS)
    INCLUDE += conandeps["conandeps"]['CPPPATH']
    LINK_SEARCH_PATH += conandeps["conandeps"]['LIBPATH']
    REQUIREMENTS += conandeps["conandeps"]['LIBS']
    DEFINITIONS += [ "-D"+ f for f in  conandeps["conandeps"]['CPPDEFINES'] ]


env['COMPONENTS'].append({'target':env['PROJECT_NAME'],
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'REGISTER':'project'
                          })