// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Kitlcd

#ifndef _KITLCD_UI_H
#define _KITLCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_EMMC;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_SDTEST;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_OTGTEST;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_I2CTEST;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_TextArea7;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_CHARGE;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_CAMTEST;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_CMMTEST;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_TextArea10;
extern lv_obj_t * ui_WIFITEST;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_TextArea9;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_CAPPLAY;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_TextArea11;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label42;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_LOCADTEST;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Panel6;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_LLMTEST;
void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_TextArea12;
extern lv_obj_t * ui_Label48;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_shuping_png);    // assets/shuping.png
LV_IMG_DECLARE(ui_img_frame_3_png);    // assets/Frame 3.png
LV_IMG_DECLARE(ui_img_frame_1_png);    // assets/Frame_1.png
LV_IMG_DECLARE(ui_img_lorawan_gateway_on_coremp135_png);    // assets/LoRaWAN Gateway on CoreMP135.png
LV_IMG_DECLARE(ui_img_lora_1_png);    // assets/Lora 1.png
LV_IMG_DECLARE(ui_img_rectangle_15_png);    // assets/Rectangle 15.png
LV_IMG_DECLARE(ui_img_rectangle_16_png);    // assets/Rectangle 16.png
LV_IMG_DECLARE(ui_img_vector_1_png);    // assets/Vector 1.png
LV_IMG_DECLARE(ui_img_vector_2_png);    // assets/Vector 2.png
LV_IMG_DECLARE(ui_img_vector_3_png);    // assets/Vector 3.png
LV_IMG_DECLARE(ui_img_battery2_png);    // assets/battery2.png
LV_IMG_DECLARE(ui_img_cm4_stack_logo1_png);    // assets/cm4_stack_logo1.png
LV_IMG_DECLARE(ui_img_1858829983);    // assets/package-1.png

// FONTS
LV_FONT_DECLARE(ui_font_mono13);
LV_FONT_DECLARE(ui_font_mono14);
LV_FONT_DECLARE(ui_font_mono15);
LV_FONT_DECLARE(ui_font_mono20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
