// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Kitlcd

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void chagne_page_test(lv_event_t * e);
void emmc_test(lv_event_t * e);
void sd_testa(lv_event_t * e);
void otg_testa(lv_event_t * e);
void i2c_testa(lv_event_t * e);
void bmi270_testa(lv_event_t * e);
void charge_testa(lv_event_t * e);
void cam_testa(lv_event_t * e);
void cmm_testa(lv_event_t * e);
void wifi_test_call(lv_event_t * e);
void cap_test_call(lv_event_t * e);
void play_cap_test_call(lv_event_t * e);
void play_test_call(lv_event_t * e);
void sys_load_call(lv_event_t * e);
void llm_test_call(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
