// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Kitlcd

#include "ui.h"

void chagne_emmc_test(lv_event_t * e)
{
	// Your code here
}

void chagne_sd_test(lv_event_t * e)
{
	// Your code here
}

void chagne_page_test(lv_event_t * e)
{
	// Your code here
}

void emmc_test(lv_event_t * e)
{
	// Your code here
}

void sd_testa(lv_event_t * e)
{
	// Your code here
}

void i2c_testa(lv_event_t * e)
{
	// Your code here
}

void charge_testa(lv_event_t * e)
{
	// Your code here
}

void cmm_testa(lv_event_t * e)
{
	// Your code here
}

void wifi_test_call(lv_event_t * e)
{
	// Your code here
}

void cap_test_call(lv_event_t * e)
{
	// Your code here
}

void play_cap_test_call(lv_event_t * e)
{
	// Your code here
}

void play_test_call(lv_event_t * e)
{
	// Your code here
}

void sys_load_call(lv_event_t * e)
{
	// Your code here
}

void otg_testa(lv_event_t * e)
{
	// Your code here
}

void cam_testa(lv_event_t * e)
{
	// Your code here
}

void bim270_testa(lv_event_t * e)
{
	// Your code here
}

void bmi270_testa(lv_event_t * e)
{
	// Your code here
}

void llm_test_call(lv_event_t * e)
{
	// Your code here
}
