# CROSS_DIR ?= /opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin
# CROSS ?= arm-linux-gnueabihf-
# PUSH_FILE?=dist
# PUSH_DIR?=/root
# PUSH_URL?=192.168.12.1
# MSSHF?=-o StrictHostKeychecking=no
# SSH_PASSWORLD?=nihao


include ../../tools/Makefile.mk
