// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_llm_product

#include "../ui/ui.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int ax_llm_connect_flage = 0;

void ui_event_TextArea(lv_event_t *e) {
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *ta         = lv_event_get_target(e);

    if (code == LV_EVENT_VALUE_CHANGED) {
        const char *text = lv_textarea_get_text(ta);
        size_t len       = strlen(text);
        if (len > 1024) {
            char truncated_text[512];
            memcpy(truncated_text, text + (len - 512), 512);
            lv_textarea_set_text(ta, truncated_text);
        }
    }
}

#include <stdio.h>
#include <string.h>
#include <time.h>
struct cpu_use_t {
    long double a[4];
    long time;
};
char *get_times()
{
    static char time_buff[16];
    time_t now           = time(NULL);
    struct tm *tm_struct = localtime(&now);
    strftime(time_buff, 9, "%H:%M:%S", tm_struct);
    return time_buff;
}
void get_memory_info(unsigned long *total_memory, unsigned long *free_memory)
{
    FILE *meminfo = fopen("/proc/meminfo", "r");
    if (meminfo == NULL) {
        perror("fopen");
        return;
    }
    char line[256];
    while (fgets(line, sizeof(line), meminfo)) {
        if (strncmp(line, "MemTotal:", 9) == 0) {
            sscanf(line, "MemTotal: %lu kB", total_memory);
        }
        if (strncmp(line, "MemAvailable:", 13) == 0) {
            sscanf(line, "MemAvailable: %lu kB", free_memory);
            break;  // Exit the loop when available memory information is found.
        }
    }
    fclose(meminfo);
}

void lvgl_task_get_system_cb(lv_timer_t *tmr)
{
    char cpu_str[16];
    char mem_str[16];
    unsigned long one;
    unsigned long two;
    static struct cpu_use_t laster = {0};
    struct cpu_use_t now;
    long double loadavg;

    FILE *fp = fopen("/proc/stat", "r");
    fscanf(fp, "%*s %Lf %Lf %Lf %Lf", &now.a[0], &now.a[1], &now.a[2], &now.a[3]);
    fclose(fp);
    now.time = LV_TICK_CUSTOM_SYS_TIME_EXPR;
    if (laster.time != 0) {
        loadavg =
            ((now.a[0] + now.a[1] + now.a[2]) - (laster.a[0] + laster.a[1] + laster.a[2])) /
            ((now.a[0] + now.a[1] + now.a[2] + now.a[3]) - (laster.a[0] + laster.a[1] + laster.a[2] + laster.a[3]));
        sprintf(cpu_str, "%d%%", (int)(loadavg * 100));
        lv_label_set_text(ui_Label1, cpu_str);
        memcpy(&laster, &now, sizeof(struct cpu_use_t));
        get_memory_info(&one, &two);
        float use = ((one * 1.0f) - (two * 1.0f)) / (one * 1.0f);
        sprintf(mem_str, "%d%%", (int)(use * 100));
        lv_label_set_text(ui_Label3, mem_str);
    } else {
        memcpy(&laster, &now, sizeof(struct cpu_use_t));
    }
    lv_label_set_text(ui_Label16, get_times());

    {
        static int old_status = 0;
        int status            = ax_llm_connect_flage;
        if (status == 0) {
            lv_color_t color     = lv_obj_get_style_bg_color(ui_Container2, LV_PART_MAIN);
            lv_color_t red_color = lv_color_hex(0xFF0000);
            if (memcmp(&color, &red_color, sizeof(lv_color_t)) == 0) {
                lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
            } else {
                lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
            }
        }
        if (status != old_status) {
            if (status) {
                lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFF1AF316), LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_label_set_text(ui_Label35, "connect");
            } else {
                lv_label_set_text(ui_Label35, "disconnect");
            }
            old_status = status;
        }
    }
}
// void lvgl_task_led_color_cb(lv_timer_t *tmr) {
//     static int i;
//     i += 70;
// }

// void add_hidden_flage() {
//     lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Chart8, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Chart7, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_HIDDEN);

//     lv_obj_add_flag(ui_Chart4, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Chart5, LV_OBJ_FLAG_HIDDEN);

//     // lv_obj_add_flag(ui_TabPage1, LV_OBJ_FLAG_HIDDEN);
//     // lv_obj_add_flag(ui_TabPage2, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_TabPage6, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_TabPage7, LV_OBJ_FLAG_HIDDEN);

//     lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN);
//     // lv_obj_add_flag(ui_TabPage5, LV_OBJ_FLAG_HIDDEN);     /// Flags

//     lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Panel9, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Label8, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Label9, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Label10, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_add_flag(ui_Label25, LV_OBJ_FLAG_HIDDEN);

//     lv_obj_add_flag(ui_TextArea10, LV_OBJ_FLAG_HIDDEN);

//     // lv_obj_add_event_cb(ui_Colorwheel3, ui_event_Colorwheel3, LV_EVENT_ALL, NULL);
//     // lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
//     // lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
//     // lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
//     // lv_obj_add_event_cb(ui_TabView3, ui_event_TabView3, LV_EVENT_ALL, NULL);

//     lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea8, ui_event_TextArea, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea, LV_EVENT_ALL, NULL);

//     lv_obj_add_flag(ui_Slider2, LV_OBJ_FLAG_HIDDEN);
//     // lv_obj_add_state(ui_Slider2, LV_STATE_DISABLED);
// }

// void cpp_init();
// void pravite_my_init() {

//     ui_Label11111 = lv_label_create(ui_TabPage8);
//     lv_obj_set_width(ui_Label11111, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label11111, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label11111, 40);
//     lv_obj_set_y(ui_Label11111, 37);
//     lv_obj_set_align(ui_Label11111, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label11111, "eth0 not connect!");

//     add_hidden_flage();
//     lv_timer_create(lvgl_task_get_system_cb, 1000, NULL);
//     lv_timer_create(lvgl_task_led_color_cb, 70, NULL);
//     cpp_init();
// }
const void *map_index_obj[] = {&ui_Panel1,  &ui_Panel2,  &ui_Panel3,  &ui_Panel5,  &ui_Panel6,
                               &ui_Panel7,  &ui_Panel8,  &ui_Panel9,  &ui_Panel10, &ui_Panel11,
                               &ui_Panel12, &ui_Panel13, &ui_Panel14, &ui_Panel15};
void start_hw_info();
void stop_hw_info();
void kit_led_switch_call(lv_event_t *e)
{
    int len            = lv_tabview_get_tab_act(ui_TabView1);
    static int old_len = 0;
    if (len == old_len) {
        return;
    }
    old_len = len;

    for (size_t i = 0; i < sizeof(map_index_obj) / sizeof(map_index_obj[0]); i++) {
        if (len == i)
            lv_obj_set_style_bg_color(*((lv_obj_t **)map_index_obj[i]), lv_color_hex(0x0300F6),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
        else
            lv_obj_set_style_bg_color(*((lv_obj_t **)map_index_obj[i]), lv_color_hex(0x7DA4DC),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    lv_tabview_t *tabview = (lv_tabview_t *)ui_TabView1;
    if (strcmp("LOAD", (const char *)tabview->map[len]) == 0) {
        start_hw_info();
    } else {
        stop_hw_info();
    }
}

void cpp_init();
void pravite_my_init()
{
    cpp_init();
    lv_timer_create(lvgl_task_get_system_cb, 1000, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea9, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea10, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea11, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea8, ui_event_TextArea, LV_EVENT_ALL, NULL);





    // printf("");
    // lv_tabview_class
}