CONFIG_TOOLCHAIN_PATH="/opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin"
CONFIG_TOOLCHAIN_PREFIX="aarch64-none-linux-gnu-"

CONFIG_SAMPLE_COMMON_ENABLED=y
CONFIG_AXCL_MSP_ENABLED=y
CONFIG_AX_8850_MSP_ENABLED=y
CONFIG_MSP_V3_6_2_ENABLED=y