// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: core135_for_ax630c_kit

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1636868526);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -144);
    lv_obj_set_y(ui_Image1, -104);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_114329946);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -80);
    lv_obj_set_y(ui_Image2, -104);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 30);
    lv_obj_set_y(ui_Label1, 10);
    lv_label_set_text(ui_Label1, "100%");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_mono13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 96);
    lv_obj_set_y(ui_Label3, 10);
    lv_label_set_text(ui_Label3, "100%");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_mono13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xC24343),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "EMMC");

    ui_Chart1 = lv_chart_create(ui_TabPage1);
    lv_obj_set_width(ui_Chart1, 266);
    lv_obj_set_height(ui_Chart1, 105);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 28);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xF00C0C),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 80, 40, 20, 10, 0, 0, 10, 20, 40, 80 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x1DEF0B),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);



    lv_obj_set_style_text_font(ui_Chart1, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 33);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -62);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "EMMC");

    ui_TextArea1 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea1, 291);
    lv_obj_set_height(ui_TextArea1, 122);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 28);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -128);
    lv_obj_set_y(ui_Label4, -75);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "R");

    ui_Label6 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -128);
    lv_obj_set_y(ui_Label6, -51);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "W");

    ui_Label7 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 79);
    lv_obj_set_y(ui_Label7, -72);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "A R:");

    ui_Label8 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 77);
    lv_obj_set_y(ui_Label8, -52);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "A W:");

    ui_Panel4 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel4, 20);
    lv_obj_set_height(ui_Panel4, 20);
    lv_obj_set_x(ui_Panel4, -98);
    lv_obj_set_y(ui_Panel4, -75);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x2CF70B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel17, 20);
    lv_obj_set_height(ui_Panel17, 20);
    lv_obj_set_x(ui_Panel17, -98);
    lv_obj_set_y(ui_Panel17, -51);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xF10A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 242);
    lv_obj_set_y(ui_Label9, 27);
    lv_label_set_text(ui_Label9, "0 M/s");

    ui_Label10 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 242);
    lv_obj_set_y(ui_Label10, 47);
    lv_label_set_text(ui_Label10, "0M/s");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "SD");

    ui_Chart3 = lv_chart_create(ui_TabPage2);
    lv_obj_set_width(ui_Chart3, 266);
    lv_obj_set_height(ui_Chart3, 105);
    lv_obj_set_x(ui_Chart3, 0);
    lv_obj_set_y(ui_Chart3, 28);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xF00C0C),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 80, 40, 20, 10, 0, 0, 10, 20, 40, 80 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x1DEF0B),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);



    lv_obj_set_style_text_font(ui_Chart3, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_TabPage2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 33);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, -62);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "SD");

    ui_TextArea3 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea3, 291);
    lv_obj_set_height(ui_TextArea3, 122);
    lv_obj_set_x(ui_TextArea3, 0);
    lv_obj_set_y(ui_TextArea3, 28);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label5 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -128);
    lv_obj_set_y(ui_Label5, -75);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "R");

    ui_Label11 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -128);
    lv_obj_set_y(ui_Label11, -51);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "W");

    ui_Label12 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 79);
    lv_obj_set_y(ui_Label12, -72);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "A R:");

    ui_Label13 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 77);
    lv_obj_set_y(ui_Label13, -52);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "A W:");

    ui_Panel19 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel19, 20);
    lv_obj_set_height(ui_Panel19, 20);
    lv_obj_set_x(ui_Panel19, -98);
    lv_obj_set_y(ui_Panel19, -75);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x2CF70B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel16, 20);
    lv_obj_set_height(ui_Panel16, 20);
    lv_obj_set_x(ui_Panel16, -98);
    lv_obj_set_y(ui_Panel16, -51);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xF10A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 242);
    lv_obj_set_y(ui_Label14, 27);
    lv_label_set_text(ui_Label14, "0 M/s");

    ui_Label15 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 242);
    lv_obj_set_y(ui_Label15, 47);
    lv_label_set_text(ui_Label15, "0 M/s");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "OTG");

    ui_Button4 = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 33);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, -62);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "OTG");

    ui_TextArea4 = lv_textarea_create(ui_TabPage3);
    lv_obj_set_width(ui_TextArea4, 291);
    lv_obj_set_height(ui_TextArea4, 122);
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, 28);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "I2C");

    ui_Button5 = lv_btn_create(ui_TabPage4);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 33);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, -62);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "I2C");

    ui_TextArea5 = lv_textarea_create(ui_TabPage4);
    lv_obj_set_width(ui_TextArea5, 291);
    lv_obj_set_height(ui_TextArea5, 122);
    lv_obj_set_x(ui_TextArea5, 0);
    lv_obj_set_y(ui_TextArea5, 28);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage10 = lv_tabview_add_tab(ui_TabView1, "IO");

    ui_Button13 = lv_btn_create(ui_TabPage10);
    lv_obj_set_width(ui_Button13, 100);
    lv_obj_set_height(ui_Button13, 33);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, -62);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "IO");

    ui_TextArea9 = lv_textarea_create(ui_TabPage10);
    lv_obj_set_width(ui_TextArea9, 291);
    lv_obj_set_height(ui_TextArea9, 122);
    lv_obj_set_x(ui_TextArea9, 0);
    lv_obj_set_y(ui_TextArea9, 28);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage11 = lv_tabview_add_tab(ui_TabView1, "TOUCH");

    ui_Button14 = lv_btn_create(ui_TabPage11);
    lv_obj_set_width(ui_Button14, 100);
    lv_obj_set_height(ui_Button14, 33);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, -62);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "TOUCH");

    ui_TextArea10 = lv_textarea_create(ui_TabPage11);
    lv_obj_set_width(ui_TextArea10, 291);
    lv_obj_set_height(ui_TextArea10, 122);
    lv_obj_set_x(ui_TextArea10, 0);
    lv_obj_set_y(ui_TextArea10, 28);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea10, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage12 = lv_tabview_add_tab(ui_TabView1, "CSI_DSI");

    ui_Button15 = lv_btn_create(ui_TabPage12);
    lv_obj_set_width(ui_Button15, 100);
    lv_obj_set_height(ui_Button15, 33);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, -62);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "CSI_DSI");

    ui_TextArea11 = lv_textarea_create(ui_TabPage12);
    lv_obj_set_width(ui_TextArea11, 291);
    lv_obj_set_height(ui_TextArea11, 122);
    lv_obj_set_x(ui_TextArea11, 0);
    lv_obj_set_y(ui_TextArea11, 28);
    lv_obj_set_align(ui_TextArea11, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea11, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "CMM");

    ui_Button6 = lv_btn_create(ui_TabPage5);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 33);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, -62);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "CMM");

    ui_TextArea6 = lv_textarea_create(ui_TabPage5);
    lv_obj_set_width(ui_TextArea6, 291);
    lv_obj_set_height(ui_TextArea6, 122);
    lv_obj_set_x(ui_TextArea6, 0);
    lv_obj_set_y(ui_TextArea6, 28);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage6 = lv_tabview_add_tab(ui_TabView1, "WIFI");

    ui_Button7 = lv_btn_create(ui_TabPage6);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 33);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, -62);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "WIFI");

    ui_TextArea7 = lv_textarea_create(ui_TabPage6);
    lv_obj_set_width(ui_TextArea7, 291);
    lv_obj_set_height(ui_TextArea7, 122);
    lv_obj_set_x(ui_TextArea7, 0);
    lv_obj_set_y(ui_TextArea7, 28);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabPage7 = lv_tabview_add_tab(ui_TabView1, "AUDIO");

    ui_Button8 = lv_btn_create(ui_TabPage7);
    lv_obj_set_width(ui_Button8, 76);
    lv_obj_set_height(ui_Button8, 33);
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, -62);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "PLAY CAP");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea8 = lv_textarea_create(ui_TabPage7);
    lv_obj_set_width(ui_TextArea8, 291);
    lv_obj_set_height(ui_TextArea8, 122);
    lv_obj_set_x(ui_TextArea8, 0);
    lv_obj_set_y(ui_TextArea8, 28);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea8, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button9 = lv_btn_create(ui_TabPage7);
    lv_obj_set_width(ui_Button9, 76);
    lv_obj_set_height(ui_Button9, 33);
    lv_obj_set_x(ui_Button9, -94);
    lv_obj_set_y(ui_Button9, -62);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "CAP");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_TabPage7);
    lv_obj_set_width(ui_Button10, 76);
    lv_obj_set_height(ui_Button10, 33);
    lv_obj_set_x(ui_Button10, 94);
    lv_obj_set_y(ui_Button10, -61);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "PLAY LOGO");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage8 = lv_tabview_add_tab(ui_TabView1, "LOAD");

    ui_Button11 = lv_btn_create(ui_TabPage8);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 33);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, -62);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "LOAD");

    ui_Label26 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -114);
    lv_obj_set_y(ui_Label26, -12);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "CPU:");

    ui_Label27 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -116);
    lv_obj_set_y(ui_Label27, 8);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "MEM:");

    ui_Label28 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -119);
    lv_obj_set_y(ui_Label28, 30);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "TEMP:");

    ui_Label29 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -113);
    lv_obj_set_y(ui_Label29, 50);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "ETH:");

    ui_Label30 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 59);
    lv_obj_set_y(ui_Label30, 87);
    lv_label_set_text(ui_Label30, "0 %");

    ui_Label31 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 58);
    lv_obj_set_y(ui_Label31, 107);
    lv_label_set_text(ui_Label31, "0 %");

    ui_Label32 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 58);
    lv_obj_set_y(ui_Label32, 129);
    lv_label_set_text(ui_Label32, "0 C");

    ui_Label33 = lv_label_create(ui_TabPage8);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 58);
    lv_obj_set_y(ui_Label33, 149);
    lv_label_set_text(ui_Label33, "disconnect");

    ui_Button12 = lv_btn_create(ui_TabPage8);
    lv_obj_set_width(ui_Button12, 100);
    lv_obj_set_height(ui_Button12, 33);
    lv_obj_set_x(ui_Button12, 70);
    lv_obj_set_y(ui_Button12, -2);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x0AEF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "POWER");

    ui_Container3 = lv_obj_create(ui_TabPage8);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 15);
    lv_obj_set_height(ui_Container3, 15);
    lv_obj_set_x(ui_Container3, 124);
    lv_obj_set_y(ui_Container3, 51);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xF30F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 15);
    lv_obj_set_height(ui_Panel1, 15);
    lv_obj_set_x(ui_Panel1, -150);
    lv_obj_set_y(ui_Panel1, 109);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x0300F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 15);
    lv_obj_set_height(ui_Panel2, 15);
    lv_obj_set_x(ui_Panel2, -129);
    lv_obj_set_y(ui_Panel2, 109);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 15);
    lv_obj_set_height(ui_Panel3, 15);
    lv_obj_set_x(ui_Panel3, -108);
    lv_obj_set_y(ui_Panel3, 109);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 15);
    lv_obj_set_height(ui_Panel5, 15);
    lv_obj_set_x(ui_Panel5, -87);
    lv_obj_set_y(ui_Panel5, 109);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 15);
    lv_obj_set_height(ui_Panel6, 15);
    lv_obj_set_x(ui_Panel6, -66);
    lv_obj_set_y(ui_Panel6, 109);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 15);
    lv_obj_set_height(ui_Panel7, 15);
    lv_obj_set_x(ui_Panel7, -45);
    lv_obj_set_y(ui_Panel7, 109);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 15);
    lv_obj_set_height(ui_Panel8, 15);
    lv_obj_set_x(ui_Panel8, -24);
    lv_obj_set_y(ui_Panel8, 109);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 15);
    lv_obj_set_height(ui_Panel9, 15);
    lv_obj_set_x(ui_Panel9, -3);
    lv_obj_set_y(ui_Panel9, 109);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 15);
    lv_obj_set_height(ui_Panel10, 15);
    lv_obj_set_x(ui_Panel10, 18);
    lv_obj_set_y(ui_Panel10, 109);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 15);
    lv_obj_set_height(ui_Panel11, 15);
    lv_obj_set_x(ui_Panel11, 39);
    lv_obj_set_y(ui_Panel11, 109);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel12, 15);
    lv_obj_set_height(ui_Panel12, 15);
    lv_obj_set_x(ui_Panel12, 60);
    lv_obj_set_y(ui_Panel12, 109);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 15);
    lv_obj_set_height(ui_Panel13, 15);
    lv_obj_set_x(ui_Panel13, 81);
    lv_obj_set_y(ui_Panel13, 109);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 15);
    lv_obj_set_height(ui_Panel14, 15);
    lv_obj_set_x(ui_Panel14, 102);
    lv_obj_set_y(ui_Panel14, 109);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel14, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel15, 15);
    lv_obj_set_height(ui_Panel15, 15);
    lv_obj_set_x(ui_Panel15, 123);
    lv_obj_set_y(ui_Panel15, 109);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel15, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -106);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "12:16:00");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 25);
    lv_obj_set_height(ui_Container2, 25);
    lv_obj_set_x(ui_Container2, 143);
    lv_obj_set_y(ui_Container2, -104);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x1AF316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image3, &ui_img_connect_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 86);
    lv_obj_set_y(ui_Label35, -106);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "disconnect");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel20, 15);
    lv_obj_set_height(ui_Panel20, 15);
    lv_obj_set_x(ui_Panel20, 144);
    lv_obj_set_y(ui_Panel20, 109);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel20, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabView1, ui_event_TabView1, LV_EVENT_ALL, NULL);

}
