CROSS_DIR := /home/nihao/work/axera_full_0316/uintv3/ax-pipeline-for-unitv3/LocalServer/toolchain/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.2.0_glibc_eabi/bin
CROSS := arm-openwrt-linux-

PUSH_FILE:=dist
PUSH_DIR:=/root
PUSH_URL:=192.168.12.1
MSSHF:=-o StrictHostKeychecking=no
SSH_USER:=root
SSH_PASSWORLD:=

include ../../tools/Makefile.mk
