// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_llm_product

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_switch_led(lv_event_t * e);
void ax_cmmc_test(lv_event_t * e);
void ax_sd_test(lv_event_t * e);
void ax_otg_test(lv_event_t * e);
void ax_cmm_test(lv_event_t * e);
void ax_cap_test(lv_event_t * e);
void ax_playcap_test(lv_event_t * e);
void ax_play_test(lv_event_t * e);
void ax_uart_test(lv_event_t * e);
void ax_sd_delect_test(lv_event_t * e);
void ax_load_test(lv_event_t * e);
void llm_power_switch(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
