// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_llm_product

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 8);
    lv_obj_set_height(ui_Panel8, 8);
    lv_obj_set_x(ui_Panel8, -100);
    lv_obj_set_y(ui_Panel8, 114);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x0300F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 8);
    lv_obj_set_height(ui_Panel10, 8);
    lv_obj_set_x(ui_Panel10, -60);
    lv_obj_set_y(ui_Panel10, 114);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 8);
    lv_obj_set_height(ui_Panel11, 8);
    lv_obj_set_x(ui_Panel11, -20);
    lv_obj_set_y(ui_Panel11, 114);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel12, 8);
    lv_obj_set_height(ui_Panel12, 8);
    lv_obj_set_x(ui_Panel12, 20);
    lv_obj_set_y(ui_Panel12, 114);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 8);
    lv_obj_set_height(ui_Panel13, 8);
    lv_obj_set_x(ui_Panel13, 60);
    lv_obj_set_y(ui_Panel13, 114);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 8);
    lv_obj_set_height(ui_Panel14, 8);
    lv_obj_set_x(ui_Panel14, 100);
    lv_obj_set_y(ui_Panel14, 115);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x7DA4DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_1636868526);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 5);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_114329946);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 58);
    lv_obj_set_y(ui_Image3, 6);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_disconnect_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 290);
    lv_obj_set_y(ui_Image4, 4);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -119);
    lv_obj_set_y(ui_Label20, -102);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "100%");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -59);
    lv_obj_set_y(ui_Label23, -102);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "100%");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -102);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "10:59:11");

    ui_Label22 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 81);
    lv_obj_set_y(ui_Label22, -102);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "disconnect");

    ui_TabView3 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView3, 320);
    lv_obj_set_height(ui_TabView3, 240);
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TabPage1 = lv_tabview_add_tab(ui_TabView3, "Title 1");

    ui_Button1 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_Button1, 142);
    lv_obj_set_height(ui_Button1, 38);
    lv_obj_set_x(ui_Button1, 76);
    lv_obj_set_y(ui_Button1, 47);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CMMC TEST");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea2, 292);
    lv_obj_set_height(ui_TextArea2, 112);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, 97);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Chart1 = lv_chart_create(ui_TabPage1);
    lv_obj_set_width(ui_Chart1, 265);
    lv_obj_set_height(ui_Chart1, 102);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 38);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 500, 1500);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 10, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xB70DFC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 80 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x0E01FF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);



    lv_obj_set_style_text_font(ui_Chart1, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel1, 20);
    lv_obj_set_height(ui_Panel1, 20);
    lv_obj_set_x(ui_Panel1, -137);
    lv_obj_set_y(ui_Panel1, -62);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xB70DFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel3, 20);
    lv_obj_set_height(ui_Panel3, 20);
    lv_obj_set_x(ui_Panel3, -137);
    lv_obj_set_y(ui_Panel3, -38);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x0E01FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -107);
    lv_obj_set_y(ui_Label2, -61);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Write");

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -107);
    lv_obj_set_y(ui_Label4, -38);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Read");

    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 222);
    lv_obj_set_y(ui_Label3, 44);
    lv_label_set_text(ui_Label3, "AR:0M/s");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 222);
    lv_obj_set_y(ui_Label5, 63);
    lv_label_set_text(ui_Label5, "AW:0M/s");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView3, "Title 2");

    ui_Button8 = lv_btn_create(ui_TabPage2);
    lv_obj_set_width(ui_Button8, 142);
    lv_obj_set_height(ui_Button8, 38);
    lv_obj_set_x(ui_Button8, 76);
    lv_obj_set_y(ui_Button8, 47);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "SD TEST");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea8 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea8, 292);
    lv_obj_set_height(ui_TextArea8, 112);
    lv_obj_set_x(ui_TextArea8, 0);
    lv_obj_set_y(ui_TextArea8, 97);
    lv_textarea_set_placeholder_text(ui_TextArea8, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Chart8 = lv_chart_create(ui_TabPage2);
    lv_obj_set_width(ui_Chart8, 265);
    lv_obj_set_height(ui_Chart8, 102);
    lv_obj_set_x(ui_Chart8, 0);
    lv_obj_set_y(ui_Chart8, 38);
    lv_obj_set_align(ui_Chart8, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart8, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart8, LV_CHART_AXIS_SECONDARY_Y, 500, 1500);
    lv_chart_set_axis_tick(ui_Chart8, LV_CHART_AXIS_PRIMARY_X, 10, 10, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart8, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart8, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart8_series_1 = lv_chart_add_series(ui_Chart8, lv_color_hex(0xB70DFC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart8_series_1_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 80 };
    lv_chart_set_ext_y_array(ui_Chart8, ui_Chart8_series_1, ui_Chart8_series_1_array);
    lv_chart_series_t * ui_Chart8_series_2 = lv_chart_add_series(ui_Chart8, lv_color_hex(0x0E01FF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart8_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart8, ui_Chart8_series_2, ui_Chart8_series_2_array);



    lv_obj_set_style_text_font(ui_Chart8, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Panel45 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel45, 20);
    lv_obj_set_height(ui_Panel45, 20);
    lv_obj_set_x(ui_Panel45, -137);
    lv_obj_set_y(ui_Panel45, -62);
    lv_obj_set_align(ui_Panel45, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel45, lv_color_hex(0xB70DFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel46 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel46, 20);
    lv_obj_set_height(ui_Panel46, 20);
    lv_obj_set_x(ui_Panel46, -137);
    lv_obj_set_y(ui_Panel46, -38);
    lv_obj_set_align(ui_Panel46, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel46, lv_color_hex(0x0E01FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -107);
    lv_obj_set_y(ui_Label48, -61);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "Write");

    ui_Label49 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -107);
    lv_obj_set_y(ui_Label49, -38);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "Read");

    ui_Label50 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 225);
    lv_obj_set_y(ui_Label50, 44);
    lv_label_set_text(ui_Label50, "AR:0M/s");
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 226);
    lv_obj_set_y(ui_Label51, 63);
    lv_label_set_text(ui_Label51, "AW:0M/s");
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView3, "Title 3");

    ui_Button7 = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_Button7, 142);
    lv_obj_set_height(ui_Button7, 38);
    lv_obj_set_x(ui_Button7, 76);
    lv_obj_set_y(ui_Button7, 47);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "OTG TEST");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea6 = lv_textarea_create(ui_TabPage3);
    lv_obj_set_width(ui_TextArea6, 292);
    lv_obj_set_height(ui_TextArea6, 112);
    lv_obj_set_x(ui_TextArea6, 0);
    lv_obj_set_y(ui_TextArea6, 97);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Chart7 = lv_chart_create(ui_TabPage3);
    lv_obj_set_width(ui_Chart7, 265);
    lv_obj_set_height(ui_Chart7, 102);
    lv_obj_set_x(ui_Chart7, 0);
    lv_obj_set_y(ui_Chart7, 38);
    lv_obj_set_align(ui_Chart7, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart7, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart7, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart7, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart7, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart7_series_1 = lv_chart_add_series(ui_Chart7, lv_color_hex(0xB70DFC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart7_series_1_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 80 };
    lv_chart_set_ext_y_array(ui_Chart7, ui_Chart7_series_1, ui_Chart7_series_1_array);
    lv_chart_series_t * ui_Chart7_series_2 = lv_chart_add_series(ui_Chart7, lv_color_hex(0x0E01FF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart7_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart7, ui_Chart7_series_2, ui_Chart7_series_2_array);



    lv_obj_set_style_text_font(ui_Chart7, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel4, 20);
    lv_obj_set_height(ui_Panel4, 20);
    lv_obj_set_x(ui_Panel4, -137);
    lv_obj_set_y(ui_Panel4, -62);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xB70DFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel9, 20);
    lv_obj_set_height(ui_Panel9, 20);
    lv_obj_set_x(ui_Panel9, -137);
    lv_obj_set_y(ui_Panel9, -38);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x0E01FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -107);
    lv_obj_set_y(ui_Label8, -61);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Write");

    ui_Label9 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -107);
    lv_obj_set_y(ui_Label9, -38);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Read");

    ui_Label10 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 225);
    lv_obj_set_y(ui_Label10, 44);
    lv_label_set_text(ui_Label10, "AW:12.8M/s");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 226);
    lv_obj_set_y(ui_Label25, 63);
    lv_label_set_text(ui_Label25, "AR:12.8M/s");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView3, "Title 4");

    ui_Button3 = lv_btn_create(ui_TabPage4);
    lv_obj_set_width(ui_Button3, 142);
    lv_obj_set_height(ui_Button3, 38);
    lv_obj_set_x(ui_Button3, 76);
    lv_obj_set_y(ui_Button3, 47);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "ETH TEST");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_TabPage4);
    lv_obj_set_width(ui_TextArea4, 292);
    lv_obj_set_height(ui_TextArea4, 112);
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, 97);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Chart3 = lv_chart_create(ui_TabPage4);
    lv_obj_set_width(ui_Chart3, 265);
    lv_obj_set_height(ui_Chart3, 102);
    lv_obj_set_x(ui_Chart3, 0);
    lv_obj_set_y(ui_Chart3, 38);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 0, 150);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 10, 10, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xB70DFC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 80 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x0E01FF),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);



    lv_obj_set_style_text_font(ui_Chart3, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_TabPage4);
    lv_obj_set_width(ui_Panel15, 20);
    lv_obj_set_height(ui_Panel15, 20);
    lv_obj_set_x(ui_Panel15, -137);
    lv_obj_set_y(ui_Panel15, -62);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xB70DFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_TabPage4);
    lv_obj_set_width(ui_Panel16, 20);
    lv_obj_set_height(ui_Panel16, 20);
    lv_obj_set_x(ui_Panel16, -137);
    lv_obj_set_y(ui_Panel16, -38);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x0E01FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -107);
    lv_obj_set_y(ui_Label26, -61);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Race");

    ui_Label27 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -107);
    lv_obj_set_y(ui_Label27, -38);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Send");

    ui_Label28 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 225);
    lv_obj_set_y(ui_Label28, 44);
    lv_label_set_text(ui_Label28, "S:0M/s");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 226);
    lv_obj_set_y(ui_Label29, 63);
    lv_label_set_text(ui_Label29, "R:0M/s");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView3, "Title 5");

    ui_Button4 = lv_btn_create(ui_TabPage5);
    lv_obj_set_width(ui_Button4, 142);
    lv_obj_set_height(ui_Button4, 38);
    lv_obj_set_x(ui_Button4, 81);
    lv_obj_set_y(ui_Button4, 25);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "RGB TEST");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel3 = lv_colorwheel_create(ui_TabPage5, true);
    lv_obj_set_width(ui_Colorwheel3, 130);
    lv_obj_set_height(ui_Colorwheel3, 130);
    lv_obj_set_x(ui_Colorwheel3, -57);
    lv_obj_set_y(ui_Colorwheel3, 31);
    lv_obj_set_align(ui_Colorwheel3, LV_ALIGN_CENTER);

    ui_Slider3 = lv_slider_create(ui_TabPage5);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 12);
    lv_obj_set_height(ui_Slider3, 130);
    lv_obj_set_x(ui_Slider3, 100);
    lv_obj_set_y(ui_Slider3, 31);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);


    ui_Panel5 = lv_obj_create(ui_TabPage5);
    lv_obj_set_width(ui_Panel5, 30);
    lv_obj_set_height(ui_Panel5, 30);
    lv_obj_set_x(ui_Panel5, -55);
    lv_obj_set_y(ui_Panel5, 30);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 113);
    lv_obj_set_y(ui_Label6, -62);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "OFF");

    ui_TabPage6 = lv_tabview_add_tab(ui_TabView3, "Title 6");

    ui_Button5 = lv_btn_create(ui_TabPage6);
    lv_obj_set_width(ui_Button5, 142);
    lv_obj_set_height(ui_Button5, 38);
    lv_obj_set_x(ui_Button5, 82);
    lv_obj_set_y(ui_Button5, 47);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x79B4F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "UART TEST");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_TabPage6);
    lv_obj_set_width(ui_TextArea3, 96);
    lv_obj_set_height(ui_TextArea3, 100);
    lv_obj_set_x(ui_TextArea3, 1);
    lv_obj_set_y(ui_TextArea3, 93);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea9 = lv_textarea_create(ui_TabPage6);
    lv_obj_set_width(ui_TextArea9, 95);
    lv_obj_set_height(ui_TextArea9, 100);
    lv_obj_set_x(ui_TextArea9, 190);
    lv_obj_set_y(ui_TextArea9, 93);
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label14 = lv_label_create(ui_TabPage6);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -99);
    lv_obj_set_y(ui_Label14, 96);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "M Recv");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_TabPage6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 92);
    lv_obj_set_y(ui_Label15, 96);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "S Recv");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_connect_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 290);
    lv_obj_set_y(ui_Image5, 4);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image5, lv_color_hex(0x08FC1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabView3, ui_event_TabView3, LV_EVENT_ALL, NULL);

}
