// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_llm_product

#ifndef _CORE135_LLM_PRODUCT_UI_H
#define _CORE135_LLM_PRODUCT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label22;
void ui_event_TabView3(lv_event_t * e);
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_TabPage1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TabPage2;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_Chart8;
extern lv_obj_t * ui_Panel45;
extern lv_obj_t * ui_Panel46;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_TabPage3;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Chart7;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_TabPage4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_TabPage5;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
void ui_event_Colorwheel3(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel3;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TabPage6;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea9;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1636868526);    // assets/grommet-icons_cpu.png
LV_IMG_DECLARE(ui_img_114329946);    // assets/ri_ram-line.png
LV_IMG_DECLARE(ui_img_disconnect_png);    // assets/disconnect.png
LV_IMG_DECLARE(ui_img_connect_png);    // assets/connect.png
LV_IMG_DECLARE(ui_img_frame_3_png);    // assets/Frame 3.png
LV_IMG_DECLARE(ui_img_frame_1_png);    // assets/Frame_1.png
LV_IMG_DECLARE(ui_img_lorawan_gateway_on_coremp135_png);    // assets/LoRaWAN Gateway on CoreMP135.png
LV_IMG_DECLARE(ui_img_lora_1_png);    // assets/Lora 1.png
LV_IMG_DECLARE(ui_img_rectangle_15_png);    // assets/Rectangle 15.png
LV_IMG_DECLARE(ui_img_rectangle_16_png);    // assets/Rectangle 16.png
LV_IMG_DECLARE(ui_img_vector_1_png);    // assets/Vector 1.png
LV_IMG_DECLARE(ui_img_vector_2_png);    // assets/Vector 2.png
LV_IMG_DECLARE(ui_img_vector_3_png);    // assets/Vector 3.png
LV_IMG_DECLARE(ui_img_battery2_png);    // assets/battery2.png
LV_IMG_DECLARE(ui_img_cm4_stack_logo1_png);    // assets/cm4_stack_logo1.png
LV_IMG_DECLARE(ui_img_1858829983);    // assets/package-1.png


LV_FONT_DECLARE(ui_font_mono13);
LV_FONT_DECLARE(ui_font_mono14);
LV_FONT_DECLARE(ui_font_mono15);
LV_FONT_DECLARE(ui_font_mono20);
void ui_event_TextArea(lv_event_t * e);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
