// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_llm_product

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_switch_led(lv_event_t * e);
void ax_cmmc_test(lv_event_t * e);
void ax_sd_test(lv_event_t * e);
void ax_otg_test(lv_event_t * e);
void ax_eth_test(lv_event_t * e);
void ax_rgb_test(lv_event_t * e);
void ax_llm_led_color(lv_event_t * e);
void ax_rgb_test_light(lv_event_t * e);
void ax_rgb_test_led(lv_event_t * e);
void ax_uart_test(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
