// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Kitlcd

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -563);
    lv_obj_set_y(ui_Button1, -322);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "EMMC");

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -563);
    lv_obj_set_y(ui_Button3, -261);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SD");

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -563);
    lv_obj_set_y(ui_Button4, -200);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "OTG");

    ui_Button5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -562);
    lv_obj_set_y(ui_Button5, -135);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "I2C");

    ui_Button6 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -426);
    lv_obj_set_y(ui_Button6, -73);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "IO");

    ui_Button7 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -557);
    lv_obj_set_y(ui_Button7, -66);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "CHARGE");

    ui_Button8 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button8, 100);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -561);
    lv_obj_set_y(ui_Button8, 4);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "CAM");

    ui_Button9 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button9, 100);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, -560);
    lv_obj_set_y(ui_Button9, 77);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "CMM");

    ui_Button10 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -564);
    lv_obj_set_y(ui_Button10, 152);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "WIFI");

    ui_Button11 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, -561);
    lv_obj_set_y(ui_Button11, 220);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "CAP_PLAY");

    ui_Button12 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button12, 100);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -443);
    lv_obj_set_y(ui_Button12, -323);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "LOAD");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -260);
    lv_obj_set_y(ui_Label2, -336);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CPU:");

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -130);
    lv_obj_set_y(ui_Label14, -337);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "MEM:");

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -26);
    lv_obj_set_y(ui_Label15, -334);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "TEMP:");

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 128);
    lv_obj_set_y(ui_Label16, -335);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "IP:");

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 406);
    lv_obj_set_y(ui_Label24, 16);
    lv_label_set_text(ui_Label24, "100%");

    ui_Label25 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 536);
    lv_obj_set_y(ui_Label25, 17);
    lv_label_set_text(ui_Label25, "100%");

    ui_Label26 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 649);
    lv_obj_set_y(ui_Label26, 17);
    lv_label_set_text(ui_Label26, "57C");

    ui_Label27 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 785);
    lv_obj_set_y(ui_Label27, 17);
    lv_label_set_text(ui_Label27, "not clinet");

    ui_EMMC = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_EMMC, 992);
    lv_obj_set_height(ui_EMMC, 654);
    lv_obj_set_x(ui_EMMC, 127);
    lv_obj_set_y(ui_EMMC, 13);
    lv_obj_set_align(ui_EMMC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EMMC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_EMMC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button13 = lv_btn_create(ui_EMMC);
    lv_obj_set_width(ui_Button13, 204);
    lv_obj_set_height(ui_Button13, 90);
    lv_obj_set_x(ui_Button13, -296);
    lv_obj_set_y(ui_Button13, -254);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "EMMC");

    ui_TextArea1 = lv_textarea_create(ui_EMMC);
    lv_obj_set_width(ui_TextArea1, 353);
    lv_obj_set_height(ui_TextArea1, 464);
    lv_obj_set_x(ui_TextArea1, -312);
    lv_obj_set_y(ui_TextArea1, 83);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_Chart1 = lv_chart_create(ui_EMMC);
    lv_obj_set_width(ui_Chart1, 486);
    lv_obj_set_height(ui_Chart1, 360);
    lv_obj_set_x(ui_Chart1, 146);
    lv_obj_set_y(ui_Chart1, 113);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xDE1717),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x1610C3),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 10, 20, 40, 80, 80, 40, 20, 15, 14, 3 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);



    ui_Label17 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -221);
    lv_obj_set_y(ui_Label17, -155);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "R:");

    ui_Label19 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -223);
    lv_obj_set_y(ui_Label19, -138);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "W:");

    ui_Panel2 = lv_obj_create(ui_Chart1);
    lv_obj_set_width(ui_Panel2, 15);
    lv_obj_set_height(ui_Panel2, 15);
    lv_obj_set_x(ui_Panel2, -205);
    lv_obj_set_y(ui_Panel2, -154);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xDE1717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Chart1);
    lv_obj_set_width(ui_Panel3, 15);
    lv_obj_set_height(ui_Panel3, 15);
    lv_obj_set_x(ui_Panel3, -205);
    lv_obj_set_y(ui_Panel3, -137);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x1610C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 157);
    lv_obj_set_y(ui_Label20, -157);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "ARS:");

    ui_Label21 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 406);
    lv_obj_set_y(ui_Label21, 17);
    lv_label_set_text(ui_Label21, "900M/s");

    ui_Label22 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 154);
    lv_obj_set_y(ui_Label22, -142);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "AWS:");

    ui_Label23 = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 406);
    lv_obj_set_y(ui_Label23, 2);
    lv_label_set_text(ui_Label23, "900M/s");

    ui_SDTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SDTEST, 992);
    lv_obj_set_height(ui_SDTEST, 654);
    lv_obj_set_x(ui_SDTEST, 127);
    lv_obj_set_y(ui_SDTEST, 13);
    lv_obj_set_align(ui_SDTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SDTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_btn_create(ui_SDTEST);
    lv_obj_set_width(ui_Button14, 204);
    lv_obj_set_height(ui_Button14, 90);
    lv_obj_set_x(ui_Button14, -296);
    lv_obj_set_y(ui_Button14, -254);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "SD");

    ui_TextArea3 = lv_textarea_create(ui_SDTEST);
    lv_obj_set_width(ui_TextArea3, 353);
    lv_obj_set_height(ui_TextArea3, 464);
    lv_obj_set_x(ui_TextArea3, -312);
    lv_obj_set_y(ui_TextArea3, 83);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");



    ui_Chart3 = lv_chart_create(ui_SDTEST);
    lv_obj_set_width(ui_Chart3, 486);
    lv_obj_set_height(ui_Chart3, 360);
    lv_obj_set_x(ui_Chart3, 146);
    lv_obj_set_y(ui_Chart3, 113);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xDE1717),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x1610C3),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 10, 20, 40, 80, 80, 40, 20, 15, 14, 3 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);



    ui_Label18 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -221);
    lv_obj_set_y(ui_Label18, -155);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "R:");

    ui_Label28 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -223);
    lv_obj_set_y(ui_Label28, -138);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "W:");

    ui_Panel5 = lv_obj_create(ui_Chart3);
    lv_obj_set_width(ui_Panel5, 15);
    lv_obj_set_height(ui_Panel5, 15);
    lv_obj_set_x(ui_Panel5, -205);
    lv_obj_set_y(ui_Panel5, -154);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xDE1717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Chart3);
    lv_obj_set_width(ui_Panel1, 15);
    lv_obj_set_height(ui_Panel1, 15);
    lv_obj_set_x(ui_Panel1, -205);
    lv_obj_set_y(ui_Panel1, -137);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x1610C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 157);
    lv_obj_set_y(ui_Label29, -157);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "ARS:");

    ui_Label30 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 406);
    lv_obj_set_y(ui_Label30, 17);
    lv_label_set_text(ui_Label30, "900M/s");

    ui_Label31 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 154);
    lv_obj_set_y(ui_Label31, -142);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "AWS:");

    ui_Label32 = lv_label_create(ui_Chart3);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 406);
    lv_obj_set_y(ui_Label32, 2);
    lv_label_set_text(ui_Label32, "900M/s");

    ui_OTGTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_OTGTEST, 992);
    lv_obj_set_height(ui_OTGTEST, 654);
    lv_obj_set_x(ui_OTGTEST, 127);
    lv_obj_set_y(ui_OTGTEST, 13);
    lv_obj_set_align(ui_OTGTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OTGTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_OTGTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_btn_create(ui_OTGTEST);
    lv_obj_set_width(ui_Button15, 204);
    lv_obj_set_height(ui_Button15, 90);
    lv_obj_set_x(ui_Button15, -296);
    lv_obj_set_y(ui_Button15, -254);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "OTG&TTYS1");

    ui_TextArea4 = lv_textarea_create(ui_OTGTEST);
    lv_obj_set_width(ui_TextArea4, 353);
    lv_obj_set_height(ui_TextArea4, 464);
    lv_obj_set_x(ui_TextArea4, -312);
    lv_obj_set_y(ui_TextArea4, 83);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");



    ui_TextArea5 = lv_textarea_create(ui_OTGTEST);
    lv_obj_set_width(ui_TextArea5, 353);
    lv_obj_set_height(ui_TextArea5, 464);
    lv_obj_set_x(ui_TextArea5, 286);
    lv_obj_set_y(ui_TextArea5, 81);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");



    ui_I2CTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_I2CTEST, 992);
    lv_obj_set_height(ui_I2CTEST, 654);
    lv_obj_set_x(ui_I2CTEST, 126);
    lv_obj_set_y(ui_I2CTEST, 13);
    lv_obj_set_align(ui_I2CTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_I2CTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_I2CTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_btn_create(ui_I2CTEST);
    lv_obj_set_width(ui_Button16, 204);
    lv_obj_set_height(ui_Button16, 90);
    lv_obj_set_x(ui_Button16, -296);
    lv_obj_set_y(ui_Button16, -254);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "I2C");

    ui_TextArea7 = lv_textarea_create(ui_I2CTEST);
    lv_obj_set_width(ui_TextArea7, 295);
    lv_obj_set_height(ui_TextArea7, 464);
    lv_obj_set_x(ui_TextArea7, -295);
    lv_obj_set_y(ui_TextArea7, 56);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");



    ui_Button25 = lv_btn_create(ui_I2CTEST);
    lv_obj_set_width(ui_Button25, 204);
    lv_obj_set_height(ui_Button25, 90);
    lv_obj_set_x(ui_Button25, 201);
    lv_obj_set_y(ui_Button25, -252);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label52 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "BMI270");

    ui_Image1 = lv_img_create(ui_I2CTEST);
    lv_img_set_src(ui_Image1, &ui_img_shuping_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 190);
    lv_obj_set_y(ui_Image1, 45);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Image1);
    lv_obj_set_width(ui_Panel4, 20);
    lv_obj_set_height(ui_Panel4, 20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x2CF456), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CHARGE = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CHARGE, 992);
    lv_obj_set_height(ui_CHARGE, 654);
    lv_obj_set_x(ui_CHARGE, 126);
    lv_obj_set_y(ui_CHARGE, 13);
    lv_obj_set_align(ui_CHARGE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CHARGE, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CHARGE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button17 = lv_btn_create(ui_CHARGE);
    lv_obj_set_width(ui_Button17, 204);
    lv_obj_set_height(ui_Button17, 90);
    lv_obj_set_x(ui_Button17, -296);
    lv_obj_set_y(ui_Button17, -254);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "charge");

    ui_TextArea6 = lv_textarea_create(ui_CHARGE);
    lv_obj_set_width(ui_TextArea6, 847);
    lv_obj_set_height(ui_TextArea6, 464);
    lv_obj_set_x(ui_TextArea6, 3);
    lv_obj_set_y(ui_TextArea6, 76);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");



    ui_Label47 = lv_label_create(ui_CHARGE);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -28);
    lv_obj_set_y(ui_Label47, -252);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Power Voltage:");

    ui_Label49 = lv_label_create(ui_CHARGE);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, 509);
    lv_obj_set_y(ui_Label49, 47);
    lv_label_set_text(ui_Label49, "0 V");

    ui_Label50 = lv_label_create(ui_CHARGE);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 297);
    lv_obj_set_y(ui_Label50, -249);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "Power Status:");

    ui_Label51 = lv_label_create(ui_CHARGE);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 830);
    lv_obj_set_y(ui_Label51, 48);
    lv_label_set_text(ui_Label51, "Discharge");

    ui_CAMTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CAMTEST, 992);
    lv_obj_set_height(ui_CAMTEST, 654);
    lv_obj_set_x(ui_CAMTEST, 126);
    lv_obj_set_y(ui_CAMTEST, 13);
    lv_obj_set_align(ui_CAMTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CAMTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CAMTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button18 = lv_btn_create(ui_CAMTEST);
    lv_obj_set_width(ui_Button18, 204);
    lv_obj_set_height(ui_Button18, 90);
    lv_obj_set_x(ui_Button18, -296);
    lv_obj_set_y(ui_Button18, -254);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "CAM");

    ui_TextArea8 = lv_textarea_create(ui_CAMTEST);
    lv_obj_set_width(ui_TextArea8, 372);
    lv_obj_set_height(ui_TextArea8, 464);
    lv_obj_set_x(ui_TextArea8, -276);
    lv_obj_set_y(ui_TextArea8, 66);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea8, "Placeholder...");



    ui_Image2 = lv_img_create(ui_CAMTEST);
    lv_obj_set_width(ui_Image2, 320);
    lv_obj_set_height(ui_Image2, 320);
    lv_obj_set_x(ui_Image2, 229);
    lv_obj_set_y(ui_Image2, 38);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CMMTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CMMTEST, 992);
    lv_obj_set_height(ui_CMMTEST, 654);
    lv_obj_set_x(ui_CMMTEST, 127);
    lv_obj_set_y(ui_CMMTEST, 13);
    lv_obj_set_align(ui_CMMTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CMMTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CMMTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button19 = lv_btn_create(ui_CMMTEST);
    lv_obj_set_width(ui_Button19, 204);
    lv_obj_set_height(ui_Button19, 90);
    lv_obj_set_x(ui_Button19, -296);
    lv_obj_set_y(ui_Button19, -254);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "CMM");

    ui_TextArea10 = lv_textarea_create(ui_CMMTEST);
    lv_obj_set_width(ui_TextArea10, 936);
    lv_obj_set_height(ui_TextArea10, 464);
    lv_obj_set_x(ui_TextArea10, 2);
    lv_obj_set_y(ui_TextArea10, 61);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea10, "Placeholder...");



    ui_WIFITEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_WIFITEST, 992);
    lv_obj_set_height(ui_WIFITEST, 654);
    lv_obj_set_x(ui_WIFITEST, 127);
    lv_obj_set_y(ui_WIFITEST, 13);
    lv_obj_set_align(ui_WIFITEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFITEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WIFITEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button20 = lv_btn_create(ui_WIFITEST);
    lv_obj_set_width(ui_Button20, 204);
    lv_obj_set_height(ui_Button20, 90);
    lv_obj_set_x(ui_Button20, -296);
    lv_obj_set_y(ui_Button20, -254);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "WIFI");

    ui_TextArea9 = lv_textarea_create(ui_WIFITEST);
    lv_obj_set_width(ui_TextArea9, 936);
    lv_obj_set_height(ui_TextArea9, 464);
    lv_obj_set_x(ui_TextArea9, 2);
    lv_obj_set_y(ui_TextArea9, 61);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");



    ui_Label46 = lv_label_create(ui_WIFITEST);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 42);
    lv_obj_set_y(ui_Label46, -248);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "Please measure multiple times.\nRSSI Reference : -25");

    ui_CAPPLAY = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CAPPLAY, 992);
    lv_obj_set_height(ui_CAPPLAY, 654);
    lv_obj_set_x(ui_CAPPLAY, 126);
    lv_obj_set_y(ui_CAPPLAY, 13);
    lv_obj_set_align(ui_CAPPLAY, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CAPPLAY, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CAPPLAY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button21 = lv_btn_create(ui_CAPPLAY);
    lv_obj_set_width(ui_Button21, 204);
    lv_obj_set_height(ui_Button21, 90);
    lv_obj_set_x(ui_Button21, -296);
    lv_obj_set_y(ui_Button21, -254);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "CAP");

    ui_TextArea11 = lv_textarea_create(ui_CAPPLAY);
    lv_obj_set_width(ui_TextArea11, 936);
    lv_obj_set_height(ui_TextArea11, 464);
    lv_obj_set_x(ui_TextArea11, 2);
    lv_obj_set_y(ui_TextArea11, 61);
    lv_obj_set_align(ui_TextArea11, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea11, "Placeholder...");



    ui_Button22 = lv_btn_create(ui_CAPPLAY);
    lv_obj_set_width(ui_Button22, 204);
    lv_obj_set_height(ui_Button22, 90);
    lv_obj_set_x(ui_Button22, -32);
    lv_obj_set_y(ui_Button22, -252);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "PLAY CAP");

    ui_Button23 = lv_btn_create(ui_CAPPLAY);
    lv_obj_set_width(ui_Button23, 204);
    lv_obj_set_height(ui_Button23, 90);
    lv_obj_set_x(ui_Button23, 261);
    lv_obj_set_y(ui_Button23, -254);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "PLAY LOGO");

    ui_LOCADTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LOCADTEST, 992);
    lv_obj_set_height(ui_LOCADTEST, 654);
    lv_obj_set_x(ui_LOCADTEST, 127);
    lv_obj_set_y(ui_LOCADTEST, 13);
    lv_obj_set_align(ui_LOCADTEST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LOCADTEST, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_LOCADTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button24 = lv_btn_create(ui_LOCADTEST);
    lv_obj_set_width(ui_Button24, 204);
    lv_obj_set_height(ui_Button24, 90);
    lv_obj_set_x(ui_Button24, -296);
    lv_obj_set_y(ui_Button24, -254);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "LOAD");

    ui_Label45 = lv_label_create(ui_LOCADTEST);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 16);
    lv_obj_set_y(ui_Label45, 46);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "LOAD TEST");

    ui_Spinner1 = lv_spinner_create(ui_LOCADTEST, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 296);
    lv_obj_set_height(ui_Spinner1, 296);
    lv_obj_set_x(ui_Spinner1, 24);
    lv_obj_set_y(ui_Spinner1, 48);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 413);
    lv_obj_set_y(ui_Label33, -334);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "10:42:01");

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 20);
    lv_obj_set_height(ui_Panel6, 20);
    lv_obj_set_x(ui_Panel6, 101);
    lv_obj_set_y(ui_Panel6, -335);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button26 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button26, 100);
    lv_obj_set_height(ui_Button26, 50);
    lv_obj_set_x(ui_Button26, -558);
    lv_obj_set_y(ui_Button26, 295);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label53 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "AI MODE");

    ui_LLMTEST = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LLMTEST, 992);
    lv_obj_set_height(ui_LLMTEST, 654);
    lv_obj_set_x(ui_LLMTEST, 127);
    lv_obj_set_y(ui_LLMTEST, 13);
    lv_obj_set_align(ui_LLMTEST, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LLMTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button27 = lv_btn_create(ui_LLMTEST);
    lv_obj_set_width(ui_Button27, 204);
    lv_obj_set_height(ui_Button27, 90);
    lv_obj_set_x(ui_Button27, -296);
    lv_obj_set_y(ui_Button27, -254);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label55 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "LLM");

    ui_TextArea12 = lv_textarea_create(ui_LLMTEST);
    lv_obj_set_width(ui_TextArea12, 936);
    lv_obj_set_height(ui_TextArea12, 464);
    lv_obj_set_x(ui_TextArea12, 2);
    lv_obj_set_y(ui_TextArea12, 61);
    lv_obj_set_align(ui_TextArea12, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea12, "Placeholder...");



    ui_Label48 = lv_label_create(ui_LLMTEST);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 149);
    lv_obj_set_y(ui_Label48, -253);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48,
                      "Connect to the local device via TCP to activate the LLM function. \nThe wake word is \"nihaonihao\".\n Once activated successfully,\n voice interaction can be initiated.");

    ui_Panel7 = lv_obj_create(ui_LLMTEST);
    lv_obj_set_width(ui_Panel7, 50);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, 429);
    lv_obj_set_y(ui_Panel7, -249);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xF00C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);

}
