# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())



if 'CONFIG_PORTDUINO_ENABLED' in os.environ:
    check_component('framework-portduino')
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=['gpiod_component']
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=[]
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]
    SRCS += append_srcs_dir(ADir("../../github_source/framework-portduino/cores"))
    SRCS += append_srcs_dir(ADir("../../github_source/framework-portduino/ArduinoCore-API/api"))
    INCLUDE.append(ADir('../../github_source/framework-portduino/cores/portduino'))
    INCLUDE.append(ADir('../../github_source/framework-portduino/ArduinoCore-API/api'))
    PRIVATE_INCLUDE.append(ADir('../../github_source/framework-portduino/cores/portduino/FS'))

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'static'
                            })
