
CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
# CONFIG_LVGL_COMPONENT_ENABLED=y
# CONFIG_LVGL_COMPONENT_LVGL=y
# CONFIG_LVGL_COMPONENT_LV_DRIVERS=y
CONFIG_DEVICE_DRIVER_ENABLED=y
CONFIG_DEVICE_I2C_ENABLED=y
CONFIG_DEVICE_UART_ENABLED=y
CONFIG_LHV_ENABLED=y
# CONFIG_LHV_WITH_KCP is not set
CONFIG_LHV_WITH_PROTOCOL=y
CONFIG_LHV_WITH_EVPP=y
CONFIG_LHV_WITH_HTTP=y
CONFIG_LHV_WITH_WITH_HTTP_CLIENT=y
CONFIG_UTILITIES_ENABLED=y
# CONFIG_NNG_ENABLED=y
# CONFIG_CJSON_ENABLED=y