# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

if 'CONFIG_AX_620E_MSP_ENABLED' in os.environ:
    MSP_PATH = ''
    if 'CONFIG_MSP_V2_0_0_ENABLED' in os.environ:
        MSP_PATH = os.environ.get('EXT_MSP_PATH', check_wget_down("https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_msp.tar.gz", 'm5stack_msp.tar.gz'))
    
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=['']
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]
    
    env["MSP_PATH"] = MSP_PATH
    # , os.path.join(MSP_PATH, 'sample/common')
    INCLUDE += [os.path.join(MSP_PATH, 'out/arm64_glibc/include'), os.path.join(MSP_PATH, 'sample'), os.path.join(MSP_PATH, 'sample/rtsp')]
    LINK_SEARCH_PATH += [os.path.join(MSP_PATH, 'out/arm64_glibc/lib')]
    REQUIREMENTS += ['dl', 'm', 'pthread']
    third_party = ['drm','faac','fdk-aac','ffmpeg','libsamplerate','mp4','opencv','opus','tinyalsa']
    for dirn in third_party:
        INCLUDE.append(os.path.join(MSP_PATH,'third-party',dirn,'include'))
        LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party',dirn,'lib/arm64/glibc'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/tinyalsa/include/tinyalsa'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/live/out/arm64/glibc/include'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/live/out/arm64/glibc/lib'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/openssl/arm64/include'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/openssl/arm64/glibc/lib'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'app/lib'))

    if 'CONFIG_SAMPLE_COMMON_ENABLED' in os.environ:
        if 'CONFIG_MSP_V2_0_0_ENABLED' in os.environ:
            INCLUDE.append(os.path.join(MSP_PATH,'sample/common'))
            SRCS += AGlob(os.path.join(MSP_PATH,'sample/common/*.c*'))

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'static'
                            })

if 'CONFIG_AX_650C_MSP_ENABLED' in os.environ:
    MSP_PATH = ''
    if 'CONFIG_AX650_MSP_V3_6_2_ENABLED' in os.environ:
        MSP_PATH = os.environ.get('EXT_MSP_PATH', check_wget_down("https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_ax650n_msp.tar.gz", 'm5stack_ax650n_msp_3.6.2.tar.gz'))
    if 'CONFIG_AX650_MSP_V3_6_4_ENABLED' in os.environ:
        MSP_PATH = os.environ.get('EXT_MSP_PATH', check_wget_down("https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_ax650n_msp_3.6.4.tar.gz", 'm5stack_ax650n_msp_3.6.4.tar.gz'))

    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=['']
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]
    
    env["MSP_PATH"] = MSP_PATH
    # , os.path.join(MSP_PATH, 'sample/common')
    INCLUDE += [os.path.join(MSP_PATH, 'out/include'), os.path.join(MSP_PATH, 'sample'), os.path.join(MSP_PATH, 'sample/rtsp')]
    LINK_SEARCH_PATH += [os.path.join(MSP_PATH, 'out/lib')]
    REQUIREMENTS += ['dl', 'm', 'pthread']
    third_party = ['drm','faac','fdk-aac','ffmpeg','libsamplerate','mp4','opencv','opus','tinyalsa']
    for dirn in third_party:
        INCLUDE.append(os.path.join(MSP_PATH,'third-party',dirn,'include'))
        LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party',dirn,'lib/arm64/glibc'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/tinyalsa/include/tinyalsa'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/live/out/include/liveMedia'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/live/out/include/groupsock'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/live/out/include/UsageEnvironment'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/live/out/include/BasicUsageEnvironment'))
    INCLUDE.append(os.path.join(MSP_PATH,'component/isp_proton/sensor/platform/tcm'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/libsamplerate/lib'))
    INCLUDE.append(os.path.join(MSP_PATH,'third-party/openssl/include'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/openssl/arm64/glibc/lib'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/tinyalsa/lib'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/fdk-aac/lib'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'third-party/opus/lib'))
    LINK_SEARCH_PATH.append(os.path.join(MSP_PATH,'app/lib'))

    if 'CONFIG_SAMPLE_COMMON_ENABLED' in os.environ:
        INCLUDE.append(os.path.join(MSP_PATH,'sample/common'))
        SRCS += AGlob(os.path.join(MSP_PATH,'sample/common/*.c*'))

    if 'CONFIG_HAL_COMMON_ENABLED' in os.environ:
        INCLUDE.append(ADir('hal_common/ax650_3_6_4'))
        INCLUDE.append(ADir('hal_common/hal'))
        SRCS += AGlob('hal_common/ax650_3_6_4/*.c*')
        INCLUDE.append(os.path.join(MSP_PATH,'sample/npu/include'))
        INCLUDE.append(os.path.join(MSP_PATH,'third-party','opencv-4.5.5','include/opencv4'))
        REQUIREMENTS += ['ax_engine', 'ax_interpreter', 'ax_sys', 'ax_ivps', 'ax_venc']
        # LINK_SEARCH_PATH+=[os.path.join(MSP_PATH,'third-party','opencv-4.5.5','lib'),os.path.join(MSP_PATH,'third-party','opencv-4.5.5','lib/opencv4/3rdparty')]
        # LDFLAGS += '-lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_videoio -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_videoio -l:liblibtiff.a  -l:liblibopenjp2.a -l:liblibjpeg-turbo.a -l:liblibwebp.a -l:liblibpng.a -l:libittnotify.a'.split()

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'static'
                            })